global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
  #Nota: cambiar el target para el que genere minikube para el servicio de flotas-service
    metrics_path: 'actuator/prometheus'
    static_configs:
      - targets: ['192.168.49.2:31623']
