apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  #Nota: cambiar el target para el que genere minikube para el servicio de flotas-service
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        metrics_path: 'actuator/prometheus'
        static_configs:
          - targets: ['192.168.49.2:31623']
